/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsAuth = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:e5928498-fcfd-44d5-98bc-e1442f9728d0",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_sPhpDpr5x",
    "aws_user_pools_web_client_id": "7t1vkjqhvsbp5h6f079prndgp9",
    "oauth": {}
};


export default awsAuth;
